version: '{branch}-{build}'
configuration: RelWithDebInfo
clone_folder: C:\Textractor
skip_branch_with_pr: false

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    arch: x64
    platform: x64
    qtbin: msvc2019_64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    arch: x86
    platform: Win32
    qtbin: msvc2019

before_build:
  - git submodule update --init
  - cd C:\
  - mkdir %arch%
  - cd %arch%
  - cmake -G "Visual Studio 16 2019" -A "%platform%" -DQt5_DIR="C:\Qt\5.15\%qtbin%\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DVERSION="" ../Textractor

build:
  project: C:\%arch%\Textractor.sln
  parallel: false
  verbosity: normal

after_build:
  - 7z a Textractor-Alpha%APPVEYOR_BUILD_NUMBER%-%arch%.zip C:\Textractor\builds\RelWithDebInfo_%arch%\*
  - appveyor PushArtifact Textractor-Alpha%APPVEYOR_BUILD_NUMBER%-%arch%.zip

notifications:
- provider: Email
  to:
  - akashmozumdar@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
